<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class QuestionnaireSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $questionnaires = [
            'businessModelQuestions' => [
                [
                    'id' => 'entity_role',
                    'title' => 'Company Role',
                    'message' => "Which best describes your company's role?",
                    'type' => 'select',
                    'options' => ['Program Manager', 'Sponsor Bank', 'Platform Provider', 'Direct MSB', 'Compliance Vendor', 'Fintech App', 'Other'],
                    'required' => true,
                ],
                [
                    'id' => 'entity_role_other',
                    'title' => 'Other Role Description',
                    'message' => 'Describe your role',
                    'type' => 'text',
                    'required' => true,
                    'placeholder' => 'Describe your company\'s role',
                    'depends_on' => ['question_id' => 'entity_role', 'value' => 'Other'],
                ],
                [
                    'id' => 'entity_financial_products',
                    'title' => 'Financial Products & Services',
                    'message' => 'What financial products or services do you offer?',
                    'type' => 'checkbox',
                    'options' => ['Checking/Deposit Accounts', 'Credit/Loans', 'BNPL', 'Debit/Prepaid Cards', 'International Remittances', 'Wire Transfers', 'ACH Payments', 'FX', 'Stablecoins', 'Crypto', 'Digital Wallets', 'Insurance', 'Securities', 'Other'],
                    'required' => true,
                ],
                [
                    'id' => 'entity_financial_products_other',
                    'title' => 'Other Products Description',
                    'message' => 'Describe other products or services',
                    'type' => 'textarea',
                    'required' => true,
                    'placeholder' => 'Describe your other products or services',
                    'depends_on' => ['question_id' => 'entity_financial_products', 'value' => ['Other']],
                ],
                [
                    'id' => 'entity_delivery_channels',
                    'title' => 'Service Delivery Channels',
                    'message' => 'How do customers access your services?',
                    'type' => 'checkbox',
                    'options' => ['Mobile App', 'Website', 'Physical Branch', 'API/Embedded', 'Agent Network', 'ATM/Kiosk', 'Other'],
                    'required' => true,
                ],
                [
                    'id' => 'entity_delivery_channels_other',
                    'title' => 'Other Delivery Channels',
                    'message' => 'Describe other delivery channels',
                    'type' => 'textarea',
                    'required' => true,
                    'placeholder' => 'Describe your other delivery channels',
                    'depends_on' => ['question_id' => 'entity_delivery_channels', 'value' => ['Other']],
                ],
                [
                    'id' => 'entity_payment_rails',
                    'title' => 'Payment Rails & Funding Methods',
                    'message' => 'What payment rails or funding methods are used?',
                    'type' => 'checkbox',
                    'options' => ['ACH', 'Wire', 'Cash', 'Checks', 'Crypto', 'Debit Card', 'Stablecoin', 'Credit Card', 'FX', 'Other'],
                    'required' => true,
                ],
                [
                    'id' => 'entity_payment_rails_other',
                    'title' => 'Other Payment Methods',
                    'message' => 'Describe other payment methods',
                    'type' => 'textarea',
                    'required' => true,
                    'placeholder' => 'Describe your other payment methods',
                    'depends_on' => ['question_id' => 'entity_payment_rails', 'value' => ['Other']],
                ],
                [
                    'id' => 'entity_uses_licensed_third_party_vendors',
                    'title' => 'Third Party Dependencies',
                    'message' => 'Do you rely on a licensed third party to offer financial services?',
                    'type' => 'select',
                    'options' => ['Yes', 'No'],
                    'required' => true,
                ],
                [
                    'id' => 'entity_third_party_details',
                    'title' => 'Third Party Details',
                    'message' => 'Enter name and role of third party',
                    'type' => 'textarea',
                    'required' => true,
                    'placeholder' => 'Enter name and role of third party (e.g., SynapseFI – payment processing & settlement)',
                    'depends_on' => ['question_id' => 'entity_uses_licensed_third_party_vendors', 'value' => 'Yes'],
                ],
                [
                    'id' => 'entity_business_model_details',
                    'title' => 'Additional Business Model Details',
                    'message' => 'Any additional details about your business model?',
                    'type' => 'textarea',
                    'required' => false,
                    'placeholder' => 'Optional catch-all for additional business model details',
                ],
            ],
            'customerOnboardingQuestions' => [
                [
                    'id' => 'entity_customer_type',
                    'title' => 'Customer Types',
                    'message' => 'Who are your typical customers?',
                    'type' => 'select',
                    'options' => ['Consumers (individuals)', 'Businesses (entities)', 'Both'],
                    'required' => true,
                ],
                [
                    'id' => 'entity_customer_kyc_information',
                    'title' => 'Consumer Information Collection',
                    'message' => 'What consumer information do you collect and verify?',
                    'type' => 'checkbox',
                    'options' => ['Full Name', 'Date of Birth', 'Address', 'SSN/TIN', 'Govt ID', 'Selfie/Photo', 'Other'],
                    'required' => true,
                ],
                [
                    'id' => 'entity_customer_kyc_methods',
                    'title' => 'Consumer Identity Verification',
                    'message' => 'How is consumer identity verified?',
                    'type' => 'select',
                    'options' => ['Manual', 'Vendor', 'Both'],
                    'required' => true,
                ],
                [
                    'id' => 'entity_customer_kyc_vendor_name',
                    'title' => 'Consumer KYC Vendor',
                    'message' => 'Consumer KYC vendor (if applicable)',
                    'type' => 'text',
                    'required' => false,
                    'placeholder' => 'Enter vendor name (e.g., Persona)',
                    'depends_on' => ['question_id' => 'entity_customer_kyc_methods', 'value' => 'Vendor'],
                ],
                [
                    'id' => 'entity_customer_kyb_information',
                    'title' => 'Business Information Collection',
                    'message' => 'What business information do you collect and verify?',
                    'type' => 'checkbox',
                    'options' => ['Business Name', 'Incorporation Docs', 'EIN/TIN', 'Address', 'UBO Names', 'UBO IDs', 'Control Person', 'Other'],
                    'required' => true,
                ],
                [
                    'id' => 'entity_customer_kyb_methods',
                    'title' => 'Business Identity Verification',
                    'message' => 'How is business identity verified?',
                    'type' => 'select',
                    'options' => ['Manual', 'Vendor', 'Both'],
                    'required' => true,
                ],
                [
                    'id' => 'entity_customer_kyb_vendor',
                    'title' => 'Business KYC Vendor',
                    'message' => 'Business KYC vendor (if applicable)',
                    'type' => 'text',
                    'required' => false,
                    'placeholder' => 'Enter vendor name (e.g., Persona)',
                    'depends_on' => ['question_id' => 'entity_customer_kyb_methods', 'value' => 'Vendor'],
                ],
                [
                    'id' => 'entity_customer_primary_reseidence',
                    'title' => 'Customer Primary Residence',
                    'message' => 'Where do your customers primarily reside or transact from?',
                    'type' => 'select',
                    'options' => ['US', 'Canada', 'UK', 'Other'],
                    'required' => true,
                ],
            ],
            'customerGeographyQuestions' => [
                [
                    'id' => 'entity_customer_geography',
                    'title' => 'Customer Locations',
                    'message' => 'Where are your customers located?',
                    'type' => 'checkbox',
                    'options' => ['US', 'Canada', 'Latin America', 'Africa', 'Middle East', 'Asia', 'Europe', 'Other'],
                    'required' => true,
                ],
                [
                    'id' => 'entity_customer_geography_other',
                    'title' => 'Other Customer Locations',
                    'message' => 'List other countries or regions',
                    'type' => 'textarea',
                    'required' => true,
                    'placeholder' => 'List other countries or regions',
                    'depends_on' => ['question_id' => 'entity_customer_geography', 'value' => ['Other']],
                ],
                [
                    'id' => 'entity_high_risk_customer_types',
                    'title' => 'High-Risk Customer Types',
                    'message' => 'Do you serve or onboard any high-risk customer types or use cases?',
                    'type' => 'checkbox',
                    'options' => ['Crypto-related', 'Cross-border Payments', 'Charities/NGOs', 'Gambling', 'Cannabis', 'Other'],
                    'required' => true,
                ],
                [
                    'id' => 'entity_high_risk_customer_types_other',
                    'title' => 'Other High-Risk Categories',
                    'message' => 'Describe other high-risk categories',
                    'type' => 'textarea',
                    'required' => true,
                    'placeholder' => 'Describe other high-risk categories',
                    'depends_on' => ['question_id' => 'entity_high_risk_customer_types', 'value' => ['Other']],
                ],
                [
                    'id' => 'entity_foreign_operations',
                    'title' => 'Foreign Operations',
                    'message' => 'Does your company have foreign operations, employees, or offices?',
                    'type' => 'select',
                    'options' => ['Yes', 'No'],
                    'required' => true,
                ],
                [
                    'id' => 'entity_foreign_operations_countries',
                    'title' => 'Foreign Operations Countries',
                    'message' => 'Which countries?',
                    'type' => 'textarea',
                    'required' => true,
                    'placeholder' => 'List the countries where you have operations, employees, or offices',
                    'depends_on' => ['question_id' => 'entity_foreign_operations', 'value' => 'Yes'],
                ],
            ],
            'transactionMonitoringQuestions' => [
                [
                    'id' => 'entity_customer_transacation_monitoring_program',
                    'title' => 'Transaction Monitoring Program',
                    'message' => 'Do you have a transaction monitoring program?',
                    'type' => 'select',
                    'options' => ['Yes', 'No'],
                    'required' => true,
                ],
                [
                    'id' => 'entity_customer_transacation_monitoring_activity_types',
                    'title' => 'Monitored Activity Types',
                    'message' => 'What types of activity are monitored?',
                    'type' => 'checkbox',
                    'options' => ['Structuring', 'High Velocity', 'Offshore Wires', 'Unusual Patterns', 'High-Risk Jurisdictions', 'High-Risk MCCs', 'ID Theft', 'Other'],
                    'required' => true,
                    'depends_on' => ['question_id' => 'entity_customer_transacation_monitoring_program', 'value' => 'Yes'],
                ],
                [
                    'id' => 'entity_customer_transacation_monitoring_process',
                    'title' => 'Monitoring System Type',
                    'message' => 'Is your monitoring system manual, automated, or both?',
                    'type' => 'select',
                    'options' => ['Manual', 'Automated', 'Hybrid'],
                    'required' => true,
                    'depends_on' => ['question_id' => 'entity_customer_transacation_monitoring_program', 'value' => 'Yes'],
                ],
                [
                    'id' => 'entity_customer_transacation_monitoring_reviewer',
                    'title' => 'Alert Review Process',
                    'message' => 'Who reviews alerts and escalates red flags?',
                    'type' => 'select',
                    'options' => ['Compliance Team', 'CCO', 'Operations', 'Other'],
                    'required' => true,
                    'depends_on' => ['question_id' => 'entity_customer_transacation_monitoring_program', 'value' => 'Yes'],
                ],
                [
                    'id' => 'entity_customer_transacation_monitoring_reporting',
                    'title' => 'Suspicious Activity Reporting',
                    'message' => 'Who do you report suspicious activity to (if applicable)?',
                    'type' => 'checkbox',
                    'options' => ['FinCEN', 'Sponsor Bank', 'Internal Only', 'Other'],
                    'required' => true,
                    'depends_on' => ['question_id' => 'entity_customer_transacation_monitoring_program', 'value' => 'Yes'],
                ],
                [
                    'id' => 'entity_customer_transacation_monitoring_sar_filing',
                    'title' => 'SAR/UAR Filing',
                    'message' => 'Do you file SARs or UARs?',
                    'type' => 'select',
                    'options' => ['Yes', 'No', 'Not Applicable'],
                    'required' => true,
                    'depends_on' => ['question_id' => 'entity_customer_transacation_monitoring_program', 'value' => 'Yes'],
                ],
                [
                    'id' => 'entity_customer_transacation_monitoring_additional_details',
                    'title' => 'Additional Monitoring Details',
                    'message' => 'Additional details about your monitoring or reporting?',
                    'type' => 'textarea',
                    'required' => false,
                    'placeholder' => 'Optional additional details about your monitoring or reporting',
                ],
            ],
            'ofacSanctionsQuestions' => [
                [
                    'id' => 'entity_customer_sanction_screening_process',
                    'title' => 'Sanctions Screening Process',
                    'message' => 'Do you have a sanctions screening process?',
                    'type' => 'select',
                    'options' => ['Yes', 'No'],
                    'required' => true,
                ],
                [
                    'id' => 'entity_customer_sanction_screening_scope',
                    'title' => 'Screening Scope',
                    'message' => 'Who or what do you screen?',
                    'type' => 'checkbox',
                    'options' => ['Customers at onboarding', 'Customers ongoing', 'Transactions', 'Vendors', 'Other'],
                    'required' => true,
                    'depends_on' => ['question_id' => 'entity_customer_sanction_screening_process', 'value' => 'Yes'],
                ],
                [
                    'id' => 'entity_customer_sanction_screening_vendor',
                    'title' => 'Screening Vendor Usage',
                    'message' => 'Do you use a vendor for screening?',
                    'type' => 'select',
                    'options' => ['Yes', 'No'],
                    'required' => true,
                    'depends_on' => ['question_id' => 'entity_customer_sanction_screening_process', 'value' => 'Yes'],
                ],
                [
                    'id' => 'entity_customer_sanction_screening_vendor_name',
                    'title' => 'Screening Vendor Name',
                    'message' => 'Screening vendor name',
                    'type' => 'text',
                    'required' => false,
                    'placeholder' => 'Enter vendor name (e.g., ComplyAdvantage)',
                    'depends_on' => ['question_id' => 'entity_customer_sanction_screening_vendor', 'value' => 'Yes'],
                ],
                [
                    'id' => 'entity_customer_sanction_screening_lists',
                    'title' => 'Watchlists Used',
                    'message' => 'Which lists are used?',
                    'type' => 'checkbox',
                    'options' => ['OFAC SDN', 'UN', 'EU', 'UK', 'PEP', 'Other'],
                    'required' => true,
                    'depends_on' => ['question_id' => 'entity_customer_sanction_screening_process', 'value' => 'Yes'],
                ],
                [
                    'id' => 'entity_customer_sanction_screening_lists_other',
                    'title' => 'Other Watchlists',
                    'message' => 'Describe other watchlists',
                    'type' => 'textarea',
                    'required' => true,
                    'placeholder' => 'Describe other watchlists',
                    'depends_on' => ['question_id' => 'entity_customer_sanction_screening_lists', 'value' => ['Other']],
                ],
                [
                    'id' => 'entity_customer_sanction_screening_frequency',
                    'title' => 'Screening Frequency',
                    'message' => 'How frequently is screening performed?',
                    'type' => 'select',
                    'options' => ['Real-Time', 'Daily', 'Weekly', 'Monthly', 'Other'],
                    'required' => true,
                    'depends_on' => ['question_id' => 'entity_customer_sanction_screening_process', 'value' => 'Yes'],
                ],
                [
                    'id' => 'entity_customer_sanction_potential_matches',
                    'title' => 'Potential Match Handling',
                    'message' => 'How are potential matches handled?',
                    'type' => 'checkbox',
                    'options' => ['Escalate Internally', 'Block/Reject', 'Report to OFAC', 'Other'],
                    'required' => true,
                    'depends_on' => ['question_id' => 'entity_customer_sanction_screening_process', 'value' => 'Yes'],
                ],
                [
                    'id' => 'entity_customer_sanction_true_matches',
                    'title' => 'True Match Handling',
                    'message' => 'How are true matches handled?',
                    'type' => 'checkbox',
                    'options' => ['Report to Regulator', 'Block', 'Escalate to Bank', 'Other'],
                    'required' => true,
                ],
                [
                    'id' => 'entity_customer_sanction_additional_details',
                    'title' => 'Additional Screening Details',
                    'message' => 'Anything else you\'d like to share about your screening process?',
                    'type' => 'textarea',
                    'required' => false,
                    'placeholder' => 'Optional additional details about your screening process',
                ],
            ],
            'customerDueDiligenceQuestions' => [
                [
                    'id' => 'entity_customer_risk_rating',
                    'title' => 'Customer Risk Rating',
                    'message' => 'Do you risk rate or classify your customers?',
                    'type' => 'select',
                    'options' => ['Yes', 'No'],
                    'required' => true,
                ],
                [
                    'id' => 'entity_customer_risk_classification',
                    'title' => 'Customer Risk Classification',
                    'message' => 'How are customers classified or scored?',
                    'type' => 'checkbox',
                    'options' => ['Risk Tiering', 'Manual Review', 'Rule-Based System', 'Other'],
                    'required' => true,
                    'depends_on' => ['question_id' => 'entity_customer_risk_rating', 'value' => 'Yes'],
                ],
                [
                    'id' => 'entity_customer_edd_application',
                    'title' => 'Enhanced Due Diligence Application',
                    'message' => 'Do you apply Enhanced Due Diligence (EDD) to any customers?',
                    'type' => 'select',
                    'options' => ['Yes', 'No'],
                    'required' => true,
                ],
                [
                    'id' => 'entity_customer_edd_triggers',
                    'title' => 'EDD Triggers',
                    'message' => 'What triggers EDD?',
                    'type' => 'checkbox',
                    'options' => ['High-Risk Geography', 'High-Risk Product', 'PEP', 'Adverse Media', 'Large Transactions', 'Internal Decision', 'Other'],
                    'required' => true,
                    'depends_on' => ['question_id' => 'entity_customer_edd_application', 'value' => 'Yes'],
                ],
                [
                    'id' => 'entity_customer_edd_triggers_other',
                    'title' => 'Other EDD Triggers',
                    'message' => 'Describe other EDD triggers',
                    'type' => 'textarea',
                    'required' => true,
                    'placeholder' => 'Describe other EDD triggers',
                    'depends_on' => ['question_id' => 'entity_customer_edd_triggers', 'value' => ['Other']],
                ],
                [
                    'id' => 'entity_customer_edd_process',
                    'title' => 'EDD Process Steps',
                    'message' => 'What steps are included in your EDD process?',
                    'type' => 'checkbox',
                    'options' => ['Additional Documents', 'Senior Review', 'Source of Funds', 'Screening', 'Other'],
                    'required' => true,
                    'depends_on' => ['question_id' => 'entity_customer_edd_application', 'value' => 'Yes'],
                ],
                [
                    'id' => 'entity_customer_edd_process_other',
                    'title' => 'Other EDD Measures',
                    'message' => 'Describe other EDD measures',
                    'type' => 'textarea',
                    'required' => true,
                    'placeholder' => 'Describe other EDD measures',
                    'depends_on' => ['question_id' => 'entity_customer_edd_process', 'value' => ['Other']],
                ],
                [
                    'id' => 'entity_customer_ongoing_monitoring',
                    'title' => 'Ongoing Monitoring',
                    'message' => 'Do you conduct ongoing monitoring of high-risk customers?',
                    'type' => 'select',
                    'options' => ['Yes', 'No'],
                    'required' => true,
                ],
                [
                    'id' => 'entity_customer_due_diligence_details',
                    'title' => 'Additional Due Diligence Details',
                    'message' => 'Additional details about your due diligence process?',
                    'type' => 'textarea',
                    'required' => false,
                    'placeholder' => 'Optional catch-all for additional due diligence details',
                ],
            ],
            'trainingGovernanceQuestions' => [
                [
                    'id' => 'entity_customer_training_program',
                    'title' => 'BSA/AML and OFAC Training Program',
                    'message' => 'Do you have a BSA/AML and OFAC training program?',
                    'type' => 'select',
                    'options' => ['Yes', 'No'],
                    'required' => true,
                ],
                [
                    'id' => 'entity_customer_training_program_audience',
                    'title' => 'Training Audience',
                    'message' => 'Who receives training?',
                    'type' => 'checkbox',
                    'options' => ['Compliance Team', 'All Employees', 'Executives', 'Vendors'],
                    'required' => true,
                    'depends_on' => ['question_id' => 'entity_customer_training_program', 'value' => 'Yes'],
                ],
                [
                    'id' => 'entity_customer_training_program_schedule',
                    'title' => 'Training Schedule',
                    'message' => 'How often is training conducted?',
                    'type' => 'select',
                    'options' => ['At onboarding', 'Annually', 'Other'],
                    'required' => true,
                    'depends_on' => ['question_id' => 'entity_customer_training_program', 'value' => 'Yes'],
                ],
                [
                    'id' => 'entity_customer_training_effectiveness_testing',
                    'title' => 'Training Effectiveness Testing',
                    'message' => 'Is training effectiveness tested?',
                    'type' => 'select',
                    'options' => ['Yes', 'No'],
                    'required' => true,
                    'depends_on' => ['question_id' => 'entity_customer_training_program', 'value' => 'Yes'],
                ],
                [
                    'id' => 'entity_customer_training_retention',
                    'title' => 'Training Record Retention',
                    'message' => 'Do you retain logs or evidence of training?',
                    'type' => 'select',
                    'options' => ['Yes', 'No'],
                    'required' => true,
                    'depends_on' => ['question_id' => 'entity_customer_training_program', 'value' => 'Yes'],
                ],
                [
                    'id' => 'entity_customer_policy_ownership',
                    'title' => 'Policy Ownership',
                    'message' => 'Who owns and maintains your compliance policies?',
                    'type' => 'select',
                    'options' => ['CCO', 'CEO', 'BOD', 'GC', 'Other'],
                    'required' => true,
                ],
                [
                    'id' => 'entity_customer_policy_ownership_other',
                    'title' => 'Other Policy Owner',
                    'message' => 'If Other, please explain',
                    'type' => 'textarea',
                    'required' => true,
                    'placeholder' => 'Please explain who owns and maintains your compliance policies',
                    'depends_on' => ['question_id' => 'entity_customer_policy_ownership', 'value' => 'Other'],
                ],
            ],
            'complianceGovernanceQuestions' => [
                [
                    'id' => 'entity_CCO',
                    'title' => 'Chief Compliance Officer',
                    'message' => 'Do you have a designated Chief Compliance Officer (CCO)?',
                    'type' => 'select',
                    'options' => ['Yes', 'No'],
                    'required' => true,
                ],
                [
                    'id' => 'entity_CCO_appointment_date',
                    'title' => 'CCO Appointment Date',
                    'message' => 'When was the CCO appointed?',
                    'type' => 'text',
                    'required' => false,
                    'placeholder' => 'Enter month and year (e.g., March 2024)',
                    'depends_on' => ['question_id' => 'entity_CCO', 'value' => 'Yes'],
                ],
                [
                    'id' => 'entity_CCO_reporting_Line',
                    'title' => 'CCO Reporting Line',
                    'message' => 'Who does the CCO report to?',
                    'type' => 'select',
                    'options' => ['CEO', 'GC', 'BOD', 'Other'],
                    'required' => false,
                    'depends_on' => ['question_id' => 'entity_CCO', 'value' => 'Yes'],
                ],
                [
                    'id' => 'entity_CCO_reporting_Line_other',
                    'title' => 'Other CCO Reporting Line',
                    'message' => 'If Other, please explain',
                    'type' => 'textarea',
                    'required' => true,
                    'placeholder' => 'Please explain who the CCO reports to',
                    'depends_on' => ['question_id' => 'entity_CCO_reporting_Line', 'value' => 'Other'],
                ],
                [
                    'id' => 'entity_board_governance_committee',
                    'title' => 'Board Governance Committee',
                    'message' => 'Do you have a board or governance committee overseeing compliance?',
                    'type' => 'select',
                    'options' => ['Yes', 'No'],
                    'required' => true,
                ],
                [
                    'id' => 'entity_independent_testing',
                    'title' => 'Independent Testing',
                    'message' => 'Do you conduct independent audits or testing of your compliance program?',
                    'type' => 'select',
                    'options' => ['Yes', 'Planned', 'No'],
                    'required' => true,
                ],
                [
                    'id' => 'entity_independent_testing_frequency',
                    'title' => 'Independent Testing Frequency',
                    'message' => 'How frequently is testing performed?',
                    'type' => 'select',
                    'options' => ['Annually', 'Every 2 Years', 'As Needed', 'Other'],
                    'required' => false,
                    'depends_on' => ['question_id' => 'entity_independent_testing', 'value' => ['Yes', 'Planned']],
                ],
            ],
            'vendorOversightQuestions' => [
                [
                    'id' => 'entity_compliance_vendor_usage',
                    'title' => 'Compliance Vendor Usage',
                    'message' => 'Do you rely on any vendors to support compliance (e.g., KYC, screening, monitoring)?',
                    'type' => 'select',
                    'options' => ['Yes', 'No'],
                    'required' => true,
                ],
                [
                    'id' => 'entity_compliance_vendor_evaluation',
                    'title' => 'Vendor Evaluation Methods',
                    'message' => 'How do you evaluate or monitor compliance vendors?',
                    'type' => 'checkbox',
                    'options' => ['Policy Review', 'Security Due Diligence', 'Periodic Review', 'None'],
                    'required' => true,
                    'depends_on' => ['question_id' => 'entity_compliance_vendor_usage', 'value' => 'Yes'],
                ],
                [
                    'id' => 'entity_compliance_record_system',
                    'title' => 'Compliance Record System',
                    'message' => 'Do you use a system or vendor to maintain compliance records?',
                    'type' => 'select',
                    'options' => ['Yes', 'Manual', 'Other'],
                    'required' => true,
                ],
            ],
            'specialComplianceQuestions' => [
                [
                    'id' => 'entity_travel_rule_compliance',
                    'title' => 'Travel Rule Compliance',
                    'message' => 'Do you facilitate or send/receive transfers ≥ $3,000 (Travel Rule)?',
                    'type' => 'select',
                    'options' => ['Yes', 'No'],
                    'required' => true,
                ],
                [
                    'id' => 'entity_foreign_correspondent_accounts',
                    'title' => 'Foreign Correspondent Accounts',
                    'message' => 'Do you maintain any foreign correspondent accounts?',
                    'type' => 'select',
                    'options' => ['Yes', 'No'],
                    'required' => true,
                ],
                [
                    'id' => 'entity_private_banking_services',
                    'title' => 'Private Banking Services',
                    'message' => 'Do you offer private banking services?',
                    'type' => 'select',
                    'options' => ['Yes', 'No'],
                    'required' => true,
                ],
                [
                    'id' => 'entity_internet_gambling_gaming',
                    'title' => 'Internet Gambling/Gaming',
                    'message' => 'Do you support or facilitate internet gambling or gaming?',
                    'type' => 'select',
                    'options' => ['Yes', 'No'],
                    'required' => true,
                ],
                [
                    'id' => 'entity_monetary_instruments',
                    'title' => 'Monetary Instruments',
                    'message' => 'Do you issue or sell monetary instruments?',
                    'type' => 'select',
                    'options' => ['Yes', 'No'],
                    'required' => true,
                ],
                [
                    'id' => 'entity_physical_cash_handling',
                    'title' => 'Physical Cash Handling',
                    'message' => 'Do you deal in or accept physical cash?',
                    'type' => 'select',
                    'options' => ['Yes', 'No'],
                    'required' => true,
                ],
            ],
            'recordkeepingQuestions' => [
                [
                    'id' => 'entity_compliance_record_retention_process',
                    'title' => 'Compliance Record Retention Process',
                    'message' => 'Do you have a process to retain compliance records (e.g., KYC, SARs, alerts)?',
                    'type' => 'select',
                    'options' => ['Yes', 'No'],
                    'required' => true,
                ],
                [
                    'id' => 'entity_compliance_record_retention_period',
                    'title' => 'Record Retention Period',
                    'message' => 'What is your standard record retention period?',
                    'type' => 'select',
                    'options' => ['5 years', '7 years', 'Other'],
                    'required' => true,
                    'depends_on' => ['question_id' => 'entity_compliance_record_retention_process', 'value' => 'Yes'],
                ],
                [
                    'id' => 'entity_compliance_record_retention_period_other',
                    'title' => 'Other Retention Period',
                    'message' => 'Please specify your retention period',
                    'type' => 'textarea',
                    'required' => true,
                    'placeholder' => 'Please specify your retention period',
                    'depends_on' => ['question_id' => 'entity_compliance_record_retention_period', 'value' => 'Other'],
                ],
            ],
        ];

        // You can now insert this data into your database
        // Example: Insert into a 'questionnaires' table
        foreach ($questionnaires as $arrayName => $questions) {
            foreach ($questions as $question) {
                DB::table('questionnaires')->insert([
                    'array_name' => $arrayName,
                    'question_id' => $question['id'],
                    'title' => $question['title'],
                    'message' => $question['message'],
                    'type' => $question['type'],
                    'options' => isset($question['options']) ? json_encode($question['options']) : null,
                    'required' => $question['required'],
                    'placeholder' => $question['placeholder'] ?? null,
                    'depends_on' => isset($question['depends_on']) ? json_encode($question['depends_on']) : null,
                    'created_at' => now(),
                    'updated_at' => now(),
                ]);
            }
        }
    }
}
