<?php

namespace Database\Seeders;

use App\Models\Question;
use App\Models\Questionnaire;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class QuestionnaireSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // $questionnaires = [
        //     [
        //         'section' => 'business_model',
        //         'questions' => [
        //             [
        //                 'question_id' => 'entity_role',
        //                 'title' => 'Company Role',
        //                 'message' => "Which best describes your company's role?",
        //                 'type' => 'select',
        //                 'options' => ['Program Manager', 'Sponsor Bank', 'Platform Provider', 'Direct MSB', 'Compliance Vendor', 'Fintech App', 'Other'],
        //                 'required' => true,
        //             ],
        //             [
        //                 'question_id' => 'entity_role_other',
        //                 'title' => 'Other Role Description',
        //                 'message' => 'Describe your role',
        //                 'type' => 'text',
        //                 'required' => true,
        //                 'placeholder' => 'Describe your company\'s role',
        //                 'depends_on' => ['question_id' => 'entity_role', 'value' => 'Other'],
        //             ],
        //             [
        //                 'question_id' => 'entity_financial_products',
        //                 'title' => 'Financial Products & Services',
        //                 'message' => 'What financial products or services do you offer?',
        //                 'type' => 'checkbox',
        //                 'options' => ['Checking/Deposit Accounts', 'Credit/Loans', 'BNPL', 'Debit/Prepaid Cards', 'International Remittances', 'Wire Transfers', 'ACH Payments', 'FX', 'Stablecoins', 'Crypto', 'Digital Wallets', 'Insurance', 'Securities', 'Other'],
        //                 'required' => true,
        //             ],
        //             [
        //                 'question_id' => 'entity_financial_products_other',
        //                 'title' => 'Other Products Description',
        //                 'message' => 'Describe other products or services',
        //                 'type' => 'textarea',
        //                 'required' => true,
        //                 'placeholder' => 'Describe your other products or services',
        //                 'depends_on' => ['question_id' => 'entity_financial_products', 'value' => ['Other']],
        //             ],
        //             [
        //                 'question_id' => 'entity_delivery_channels',
        //                 'title' => 'Service Delivery Channels',
        //                 'message' => 'How do customers access your services?',
        //                 'type' => 'checkbox',
        //                 'options' => ['Mobile App', 'Website', 'Physical Branch', 'API/Embedded', 'Agent Network', 'ATM/Kiosk', 'Other'],
        //                 'required' => true,
        //             ],
        //             [
        //                 'question_id' => 'entity_delivery_channels_other',
        //                 'title' => 'Other Delivery Channels',
        //                 'message' => 'Describe other delivery channels',
        //                 'type' => 'textarea',
        //                 'required' => true,
        //                 'placeholder' => 'Describe your other delivery channels',
        //                 'depends_on' => ['question_id' => 'entity_delivery_channels', 'value' => ['Other']],
        //             ],
        //             [
        //                 'question_id' => 'entity_payment_rails',
        //                 'title' => 'Payment Rails & Funding Methods',
        //                 'message' => 'What payment rails or funding methods are used?',
        //                 'type' => 'checkbox',
        //                 'options' => ['ACH', 'Wire', 'Cash', 'Checks', 'Crypto', 'Debit Card', 'Stablecoin', 'Credit Card', 'FX', 'Other'],
        //                 'required' => true,
        //             ],
        //             [
        //                 'question_id' => 'entity_payment_rails_other',
        //                 'title' => 'Other Payment Methods',
        //                 'message' => 'Describe other payment methods',
        //                 'type' => 'textarea',
        //                 'required' => true,
        //                 'placeholder' => 'Describe your other payment methods',
        //                 'depends_on' => ['question_id' => 'entity_payment_rails', 'value' => ['Other']],
        //             ],
        //             [
        //                 'question_id' => 'entity_uses_licensed_third_party_vendors',
        //                 'title' => 'Third Party Dependencies',
        //                 'message' => 'Do you rely on a licensed third party to offer financial services?',
        //                 'type' => 'select',
        //                 'options' => ['Yes', 'No'],
        //                 'required' => true,
        //             ],
        //             [
        //                 'question_id' => 'entity_third_party_details',
        //                 'title' => 'Third Party Details',
        //                 'message' => 'Enter name and role of third party',
        //                 'type' => 'textarea',
        //                 'required' => true,
        //                 'placeholder' => 'Enter name and role of third party (e.g., SynapseFI – payment processing & settlement)',
        //                 'depends_on' => ['question_id' => 'entity_uses_licensed_third_party_vendors', 'value' => 'Yes'],
        //             ],
        //             [
        //                 'question_id' => 'entity_business_model_details',
        //                 'title' => 'Additional Business Model Details',
        //                 'message' => 'Any additional details about your business model?',
        //                 'type' => 'textarea',
        //                 'required' => false,
        //                 'placeholder' => 'Optional catch-all for additional business model details',
        //             ],
        //         ]
        //     ],
        //     [
        //         'section' => 'customer_onboarding',
        //         'questions' => [
        //             [
        //                 'question_id' => 'entity_customer_type',
        //                 'title' => 'Customer Types',
        //                 'message' => 'Who are your typical customers?',
        //                 'type' => 'select',
        //                 'options' => ['Consumers (individuals)', 'Businesses (entities)', 'Both'],
        //                 'required' => true,
        //             ],
        //             [
        //                 'question_id' => 'entity_customer_kyc_information',
        //                 'title' => 'Consumer Information Collection',
        //                 'message' => 'What consumer information do you collect and verify?',
        //                 'type' => 'checkbox',
        //                 'options' => ['Full Name', 'Date of Birth', 'Address', 'SSN/TIN', 'Govt ID', 'Selfie/Photo', 'Other'],
        //                 'required' => true,
        //             ],
        //             [
        //                 'question_id' => 'entity_customer_kyc_methods',
        //                 'title' => 'Consumer Identity Verification',
        //                 'message' => 'How is consumer identity verified?',
        //                 'type' => 'select',
        //                 'options' => ['Manual', 'Vendor', 'Both'],
        //                 'required' => true,
        //             ],
        //             [
        //                 'question_id' => 'entity_customer_kyc_vendor_name',
        //                 'title' => 'Consumer KYC Vendor',
        //                 'message' => 'Consumer KYC vendor (if applicable)',
        //                 'type' => 'text',
        //                 'required' => false,
        //                 'placeholder' => 'Enter vendor name (e.g., Persona)',
        //                 'depends_on' => ['question_id' => 'entity_customer_kyc_methods', 'value' => 'Vendor'],
        //             ],
        //             [
        //                 'question_id' => 'entity_customer_kyb_information',
        //                 'title' => 'Business Information Collection',
        //                 'message' => 'What business information do you collect and verify?',
        //                 'type' => 'checkbox',
        //                 'options' => ['Business Name', 'Incorporation Docs', 'EIN/TIN', 'Address', 'UBO Names', 'UBO IDs', 'Control Person', 'Other'],
        //                 'required' => true,
        //             ],
        //             [
        //                 'question_id' => 'entity_customer_kyb_methods',
        //                 'title' => 'Business Identity Verification',
        //                 'message' => 'How is business identity verified?',
        //                 'type' => 'select',
        //                 'options' => ['Manual', 'Vendor', 'Both'],
        //                 'required' => true,
        //             ],
        //             [
        //                 'question_id' => 'entity_customer_kyb_vendor',
        //                 'title' => 'Business KYC Vendor',
        //                 'message' => 'Business KYC vendor (if applicable)',
        //                 'type' => 'text',
        //                 'required' => false,
        //                 'placeholder' => 'Enter vendor name (e.g., Persona)',
        //                 'depends_on' => ['question_id' => 'entity_customer_kyb_methods', 'value' => 'Vendor'],
        //             ],
        //             [
        //                 'question_id' => 'entity_customer_primary_reseidence',
        //                 'title' => 'Customer Primary Residence',
        //                 'message' => 'Where do your customers primarily reside or transact from?',
        //                 'type' => 'select',
        //                 'options' => ['US', 'Canada', 'UK', 'Other'],
        //                 'required' => true,
        //             ],
        //         ]
        //     ],
        //     [
        //         'section' => 'customer_geography',
        //         'questions' => [
        //             [
        //                 'question_id' => 'entity_customer_geography',
        //                 'title' => 'Customer Locations',
        //                 'message' => 'Where are your customers located?',
        //                 'type' => 'checkbox',
        //                 'options' => ['US', 'Canada', 'Latin America', 'Africa', 'Middle East', 'Asia', 'Europe', 'Other'],
        //                 'required' => true,
        //             ],
        //             [
        //                 'question_id' => 'entity_customer_geography_other',
        //                 'title' => 'Other Customer Locations',
        //                 'message' => 'List other countries or regions',
        //                 'type' => 'textarea',
        //                 'required' => true,
        //                 'placeholder' => 'List other countries or regions',
        //                 'depends_on' => ['question_id' => 'entity_customer_geography', 'value' => ['Other']],
        //             ],
        //             [
        //                 'question_id' => 'entity_high_risk_customer_types',
        //                 'title' => 'High-Risk Customer Types',
        //                 'message' => 'Do you serve or onboard any high-risk customer types or use cases?',
        //                 'type' => 'checkbox',
        //                 'options' => ['Crypto-related', 'Cross-border Payments', 'Charities/NGOs', 'Gambling', 'Cannabis', 'Other'],
        //                 'required' => true,
        //             ],
        //             [
        //                 'question_id' => 'entity_high_risk_customer_types_other',
        //                 'title' => 'Other High-Risk Categories',
        //                 'message' => 'Describe other high-risk categories',
        //                 'type' => 'textarea',
        //                 'required' => true,
        //                 'placeholder' => 'Describe other high-risk categories',
        //                 'depends_on' => ['question_id' => 'entity_high_risk_customer_types', 'value' => ['Other']],
        //             ],
        //             [
        //                 'question_id' => 'entity_foreign_operations',
        //                 'title' => 'Foreign Operations',
        //                 'message' => 'Does your company have foreign operations, employees, or offices?',
        //                 'type' => 'select',
        //                 'options' => ['Yes', 'No'],
        //                 'required' => true,
        //             ],
        //             [
        //                 'question_id' => 'entity_foreign_operations_countries',
        //                 'title' => 'Foreign Operations Countries',
        //                 'message' => 'Which countries?',
        //                 'type' => 'textarea',
        //                 'required' => true,
        //                 'placeholder' => 'List the countries where you have operations, employees, or offices',
        //                 'depends_on' => ['question_id' => 'entity_foreign_operations', 'value' => 'Yes'],
        //             ],
        //         ]
        //     ],
        //     [
        //         'section' => 'transaction_monitoring',
        //         'questions' => [
        //             [
        //                 'question_id' => 'entity_customer_transacation_monitoring_program',
        //                 'title' => 'Transaction Monitoring Program',
        //                 'message' => 'Do you have a transaction monitoring program?',
        //                 'type' => 'select',
        //                 'options' => ['Yes', 'No'],
        //                 'required' => true,
        //             ],
        //             [
        //                 'question_id' => 'entity_customer_transacation_monitoring_activity_types',
        //                 'title' => 'Monitored Activity Types',
        //                 'message' => 'What types of activity are monitored?',
        //                 'type' => 'checkbox',
        //                 'options' => ['Structuring', 'High Velocity', 'Offshore Wires', 'Unusual Patterns', 'High-Risk Jurisdictions', 'High-Risk MCCs', 'ID Theft', 'Other'],
        //                 'required' => true,
        //                 'depends_on' => ['question_id' => 'entity_customer_transacation_monitoring_program', 'value' => 'Yes'],
        //             ],
        //             [
        //                 'question_id' => 'entity_customer_transacation_monitoring_process',
        //                 'title' => 'Monitoring System Type',
        //                 'message' => 'Is your monitoring system manual, automated, or both?',
        //                 'type' => 'select',
        //                 'options' => ['Manual', 'Automated', 'Hybrid'],
        //                 'required' => true,
        //                 'depends_on' => ['question_id' => 'entity_customer_transacation_monitoring_program', 'value' => 'Yes'],
        //             ],
        //             [
        //                 'question_id' => 'entity_customer_transacation_monitoring_reviewer',
        //                 'title' => 'Alert Review Process',
        //                 'message' => 'Who reviews alerts and escalates red flags?',
        //                 'type' => 'select',
        //                 'options' => ['Compliance Team', 'CCO', 'Operations', 'Other'],
        //                 'required' => true,
        //                 'depends_on' => ['question_id' => 'entity_customer_transacation_monitoring_program', 'value' => 'Yes'],
        //             ],
        //             [
        //                 'question_id' => 'entity_customer_transacation_monitoring_reporting',
        //                 'title' => 'Suspicious Activity Reporting',
        //                 'message' => 'Who do you report suspicious activity to (if applicable)?',
        //                 'type' => 'checkbox',
        //                 'options' => ['FinCEN', 'Sponsor Bank', 'Internal Only', 'Other'],
        //                 'required' => true,
        //                 'depends_on' => ['question_id' => 'entity_customer_transacation_monitoring_program', 'value' => 'Yes'],
        //             ],
        //             [
        //                 'question_id' => 'entity_customer_transacation_monitoring_sar_filing',
        //                 'title' => 'SAR/UAR Filing',
        //                 'message' => 'Do you file SARs or UARs?',
        //                 'type' => 'select',
        //                 'options' => ['Yes', 'No', 'Not Applicable'],
        //                 'required' => true,
        //                 'depends_on' => ['question_id' => 'entity_customer_transacation_monitoring_program', 'value' => 'Yes'],
        //             ],
        //             [
        //                 'question_id' => 'entity_customer_transacation_monitoring_additional_details',
        //                 'title' => 'Additional Monitoring Details',
        //                 'message' => 'Additional details about your monitoring or reporting?',
        //                 'type' => 'textarea',
        //                 'required' => false,
        //                 'placeholder' => 'Optional additional details about your monitoring or reporting',
        //             ],
        //         ]
        //     ],
        //     [
        //         'section' => 'ofac_sanctions',
        //         'questions' => [
        //             [
        //                 'question_id' => 'entity_customer_sanction_screening_process',
        //                 'title' => 'Sanctions Screening Process',
        //                 'message' => 'Do you have a sanctions screening process?',
        //                 'type' => 'select',
        //                 'options' => ['Yes', 'No'],
        //                 'required' => true,
        //             ],
        //             [
        //                 'question_id' => 'entity_customer_sanction_screening_scope',
        //                 'title' => 'Screening Scope',
        //                 'message' => 'Who or what do you screen?',
        //                 'type' => 'checkbox',
        //                 'options' => ['Customers at onboarding', 'Customers ongoing', 'Transactions', 'Vendors', 'Other'],
        //                 'required' => true,
        //                 'depends_on' => ['question_id' => 'entity_customer_sanction_screening_process', 'value' => 'Yes'],
        //             ],
        //             [
        //                 'question_id' => 'entity_customer_sanction_screening_vendor',
        //                 'title' => 'Screening Vendor Usage',
        //                 'message' => 'Do you use a vendor for screening?',
        //                 'type' => 'select',
        //                 'options' => ['Yes', 'No'],
        //                 'required' => true,
        //                 'depends_on' => ['question_id' => 'entity_customer_sanction_screening_process', 'value' => 'Yes'],
        //             ],
        //             [
        //                 'question_id' => 'entity_customer_sanction_screening_vendor_name',
        //                 'title' => 'Screening Vendor Name',
        //                 'message' => 'Screening vendor name',
        //                 'type' => 'text',
        //                 'required' => false,
        //                 'placeholder' => 'Enter vendor name (e.g., ComplyAdvantage)',
        //                 'depends_on' => ['question_id' => 'entity_customer_sanction_screening_vendor', 'value' => 'Yes'],
        //             ],
        //             [
        //                 'question_id' => 'entity_customer_sanction_screening_lists',
        //                 'title' => 'Watchlists Used',
        //                 'message' => 'Which lists are used?',
        //                 'type' => 'checkbox',
        //                 'options' => ['OFAC SDN', 'UN', 'EU', 'UK', 'PEP', 'Other'],
        //                 'required' => true,
        //                 'depends_on' => ['question_id' => 'entity_customer_sanction_screening_process', 'value' => 'Yes'],
        //             ],
        //             [
        //                 'question_id' => 'entity_customer_sanction_screening_lists_other',
        //                 'title' => 'Other Watchlists',
        //                 'message' => 'Describe other watchlists',
        //                 'type' => 'textarea',
        //                 'required' => true,
        //                 'placeholder' => 'Describe other watchlists',
        //                 'depends_on' => ['question_id' => 'entity_customer_sanction_screening_lists', 'value' => ['Other']],
        //             ],
        //             [
        //                 'question_id' => 'entity_customer_sanction_screening_frequency',
        //                 'title' => 'Screening Frequency',
        //                 'message' => 'How frequently is screening performed?',
        //                 'type' => 'select',
        //                 'options' => ['Real-Time', 'Daily', 'Weekly', 'Monthly', 'Other'],
        //                 'required' => true,
        //                 'depends_on' => ['question_id' => 'entity_customer_sanction_screening_process', 'value' => 'Yes'],
        //             ],
        //             [
        //                 'question_id' => 'entity_customer_sanction_potential_matches',
        //                 'title' => 'Potential Match Handling',
        //                 'message' => 'How are potential matches handled?',
        //                 'type' => 'checkbox',
        //                 'options' => ['Escalate Internally', 'Block/Reject', 'Report to OFAC', 'Other'],
        //                 'required' => true,
        //                 'depends_on' => ['question_id' => 'entity_customer_sanction_screening_process', 'value' => 'Yes'],
        //             ],
        //             [
        //                 'question_id' => 'entity_customer_sanction_true_matches',
        //                 'title' => 'True Match Handling',
        //                 'message' => 'How are true matches handled?',
        //                 'type' => 'checkbox',
        //                 'options' => ['Report to Regulator', 'Block', 'Escalate to Bank', 'Other'],
        //                 'required' => true,
        //             ],
        //             [
        //                 'question_id' => 'entity_customer_sanction_additional_details',
        //                 'title' => 'Additional Screening Details',
        //                 'message' => 'Anything else you\'d like to share about your screening process?',
        //                 'type' => 'textarea',
        //                 'required' => false,
        //                 'placeholder' => 'Optional additional details about your screening process',
        //             ],
        //         ]
        //     ],
        //     [
        //         'section' => 'customer_due_diligence',
        //         'questions' => [
        //             [
        //                 'question_id' => 'entity_customer_risk_rating',
        //                 'title' => 'Customer Risk Rating',
        //                 'message' => 'Do you risk rate or classify your customers?',
        //                 'type' => 'select',
        //                 'options' => ['Yes', 'No'],
        //                 'required' => true,
        //             ],
        //             [
        //                 'question_id' => 'entity_customer_risk_classification',
        //                 'title' => 'Customer Risk Classification',
        //                 'message' => 'How are customers classified or scored?',
        //                 'type' => 'checkbox',
        //                 'options' => ['Risk Tiering', 'Manual Review', 'Rule-Based System', 'Other'],
        //                 'required' => true,
        //                 'depends_on' => ['question_id' => 'entity_customer_risk_rating', 'value' => 'Yes'],
        //             ],
        //             [
        //                 'question_id' => 'entity_customer_edd_application',
        //                 'title' => 'Enhanced Due Diligence Application',
        //                 'message' => 'Do you apply Enhanced Due Diligence (EDD) to any customers?',
        //                 'type' => 'select',
        //                 'options' => ['Yes', 'No'],
        //                 'required' => true,
        //             ],
        //             [
        //                 'question_id' => 'entity_customer_edd_triggers',
        //                 'title' => 'EDD Triggers',
        //                 'message' => 'What triggers EDD?',
        //                 'type' => 'checkbox',
        //                 'options' => ['High-Risk Geography', 'High-Risk Product', 'PEP', 'Adverse Media', 'Large Transactions', 'Internal Decision', 'Other'],
        //                 'required' => true,
        //                 'depends_on' => ['question_id' => 'entity_customer_edd_application', 'value' => 'Yes'],
        //             ],
        //             [
        //                 'question_id' => 'entity_customer_edd_triggers_other',
        //                 'title' => 'Other EDD Triggers',
        //                 'message' => 'Describe other EDD triggers',
        //                 'type' => 'textarea',
        //                 'required' => true,
        //                 'placeholder' => 'Describe other EDD triggers',
        //                 'depends_on' => ['question_id' => 'entity_customer_edd_triggers', 'value' => ['Other']],
        //             ],
        //             [
        //                 'question_id' => 'entity_customer_edd_process',
        //                 'title' => 'EDD Process Steps',
        //                 'message' => 'What steps are included in your EDD process?',
        //                 'type' => 'checkbox',
        //                 'options' => ['Additional Documents', 'Senior Review', 'Source of Funds', 'Screening', 'Other'],
        //                 'required' => true,
        //                 'depends_on' => ['question_id' => 'entity_customer_edd_application', 'value' => 'Yes'],
        //             ],
        //             [
        //                 'question_id' => 'entity_customer_edd_process_other',
        //                 'title' => 'Other EDD Measures',
        //                 'message' => 'Describe other EDD measures',
        //                 'type' => 'textarea',
        //                 'required' => true,
        //                 'placeholder' => 'Describe other EDD measures',
        //                 'depends_on' => ['question_id' => 'entity_customer_edd_process', 'value' => ['Other']],
        //             ],
        //             [
        //                 'question_id' => 'entity_customer_ongoing_monitoring',
        //                 'title' => 'Ongoing Monitoring',
        //                 'message' => 'Do you conduct ongoing monitoring of high-risk customers?',
        //                 'type' => 'select',
        //                 'options' => ['Yes', 'No'],
        //                 'required' => true,
        //             ],
        //             [
        //                 'question_id' => 'entity_customer_due_diligence_details',
        //                 'title' => 'Additional Due Diligence Details',
        //                 'message' => 'Additional details about your due diligence process?',
        //                 'type' => 'textarea',
        //                 'required' => false,
        //                 'placeholder' => 'Optional catch-all for additional due diligence details',
        //             ],
        //         ]
        //     ],
        //     [
        //         'section' => 'training_governance',
        //         'questions' => [
        //             [
        //                 'question_id' => 'entity_customer_training_program',
        //                 'title' => 'BSA/AML and OFAC Training Program',
        //                 'message' => 'Do you have a BSA/AML and OFAC training program?',
        //                 'type' => 'select',
        //                 'options' => ['Yes', 'No'],
        //                 'required' => true,
        //             ],
        //             [
        //                 'question_id' => 'entity_customer_training_program_audience',
        //                 'title' => 'Training Audience',
        //                 'message' => 'Who receives training?',
        //                 'type' => 'checkbox',
        //                 'options' => ['Compliance Team', 'All Employees', 'Executives', 'Vendors'],
        //                 'required' => true,
        //                 'depends_on' => ['question_id' => 'entity_customer_training_program', 'value' => 'Yes'],
        //             ],
        //             [
        //                 'question_id' => 'entity_customer_training_program_schedule',
        //                 'title' => 'Training Schedule',
        //                 'message' => 'How often is training conducted?',
        //                 'type' => 'select',
        //                 'options' => ['At onboarding', 'Annually', 'Other'],
        //                 'required' => true,
        //                 'depends_on' => ['question_id' => 'entity_customer_training_program', 'value' => 'Yes'],
        //             ],
        //             [
        //                 'question_id' => 'entity_customer_training_effectiveness_testing',
        //                 'title' => 'Training Effectiveness Testing',
        //                 'message' => 'Is training effectiveness tested?',
        //                 'type' => 'select',
        //                 'options' => ['Yes', 'No'],
        //                 'required' => true,
        //                 'depends_on' => ['question_id' => 'entity_customer_training_program', 'value' => 'Yes'],
        //             ],
        //             [
        //                 'question_id' => 'entity_customer_training_retention',
        //                 'title' => 'Training Record Retention',
        //                 'message' => 'Do you retain logs or evidence of training?',
        //                 'type' => 'select',
        //                 'options' => ['Yes', 'No'],
        //                 'required' => true,
        //                 'depends_on' => ['question_id' => 'entity_customer_training_program', 'value' => 'Yes'],
        //             ],
        //             [
        //                 'question_id' => 'entity_customer_policy_ownership',
        //                 'title' => 'Policy Ownership',
        //                 'message' => 'Who owns and maintains your compliance policies?',
        //                 'type' => 'select',
        //                 'options' => ['CCO', 'CEO', 'BOD', 'GC', 'Other'],
        //                 'required' => true,
        //             ],
        //             [
        //                 'question_id' => 'entity_customer_policy_ownership_other',
        //                 'title' => 'Other Policy Owner',
        //                 'message' => 'If Other, please explain',
        //                 'type' => 'textarea',
        //                 'required' => true,
        //                 'placeholder' => 'Please explain who owns and maintains your compliance policies',
        //                 'depends_on' => ['question_id' => 'entity_customer_policy_ownership', 'value' => 'Other'],
        //             ],
        //         ]
        //     ],
        //     [
        //         'section' => 'compliance_governance',
        //         'questions' => [
        //             [
        //                 'question_id' => 'entity_CCO',
        //                 'title' => 'Chief Compliance Officer',
        //                 'message' => 'Do you have a designated Chief Compliance Officer (CCO)?',
        //                 'type' => 'select',
        //                 'options' => ['Yes', 'No'],
        //                 'required' => true,
        //             ],
        //             [
        //                 'question_id' => 'entity_CCO_appointment_date',
        //                 'title' => 'CCO Appointment Date',
        //                 'message' => 'When was the CCO appointed?',
        //                 'type' => 'text',
        //                 'required' => false,
        //                 'placeholder' => 'Enter month and year (e.g., March 2024)',
        //                 'depends_on' => ['question_id' => 'entity_CCO', 'value' => 'Yes'],
        //             ],
        //             [
        //                 'question_id' => 'entity_CCO_reporting_Line',
        //                 'title' => 'CCO Reporting Line',
        //                 'message' => 'Who does the CCO report to?',
        //                 'type' => 'select',
        //                 'options' => ['CEO', 'GC', 'BOD', 'Other'],
        //                 'required' => false,
        //                 'depends_on' => ['question_id' => 'entity_CCO', 'value' => 'Yes'],
        //             ],
        //             [
        //                 'question_id' => 'entity_CCO_reporting_Line_other',
        //                 'title' => 'Other CCO Reporting Line',
        //                 'message' => 'If Other, please explain',
        //                 'type' => 'textarea',
        //                 'required' => true,
        //                 'placeholder' => 'Please explain who the CCO reports to',
        //                 'depends_on' => ['question_id' => 'entity_CCO_reporting_Line', 'value' => 'Other'],
        //             ],
        //             [
        //                 'question_id' => 'entity_board_governance_committee',
        //                 'title' => 'Board Governance Committee',
        //                 'message' => 'Do you have a board or governance committee overseeing compliance?',
        //                 'type' => 'select',
        //                 'options' => ['Yes', 'No'],
        //                 'required' => true,
        //             ],
        //             [
        //                 'question_id' => 'entity_independent_testing',
        //                 'title' => 'Independent Testing',
        //                 'message' => 'Do you conduct independent audits or testing of your compliance program?',
        //                 'type' => 'select',
        //                 'options' => ['Yes', 'Planned', 'No'],
        //                 'required' => true,
        //             ],
        //             [
        //                 'question_id' => 'entity_independent_testing_frequency',
        //                 'title' => 'Independent Testing Frequency',
        //                 'message' => 'How frequently is testing performed?',
        //                 'type' => 'select',
        //                 'options' => ['Annually', 'Every 2 Years', 'As Needed', 'Other'],
        //                 'required' => false,
        //                 'depends_on' => ['question_id' => 'entity_independent_testing', 'value' => ['Yes', 'Planned']],
        //             ],
        //         ]
        //     ],
        //     [
        //         'section' => 'vendor_oversight',
        //         'questions' => [
        //             [
        //                 'question_id' => 'entity_compliance_vendor_usage',
        //                 'title' => 'Compliance Vendor Usage',
        //                 'message' => 'Do you rely on any vendors to support compliance (e.g., KYC, screening, monitoring)?',
        //                 'type' => 'select',
        //                 'options' => ['Yes', 'No'],
        //                 'required' => true,
        //             ],
        //             [
        //                 'question_id' => 'entity_compliance_vendor_evaluation',
        //                 'title' => 'Vendor Evaluation Methods',
        //                 'message' => 'How do you evaluate or monitor compliance vendors?',
        //                 'type' => 'checkbox',
        //                 'options' => ['Policy Review', 'Security Due Diligence', 'Periodic Review', 'None'],
        //                 'required' => true,
        //                 'depends_on' => ['question_id' => 'entity_compliance_vendor_usage', 'value' => 'Yes'],
        //             ],
        //             [
        //                 'question_id' => 'entity_compliance_record_system',
        //                 'title' => 'Compliance Record System',
        //                 'message' => 'Do you use a system or vendor to maintain compliance records?',
        //                 'type' => 'select',
        //                 'options' => ['Yes', 'Manual', 'Other'],
        //                 'required' => true,
        //             ],
        //         ]
        //     ],
        //     [
        //         'section' => 'special_compliance',
        //         'questions' => [
        //             [
        //                 'question_id' => 'entity_travel_rule_compliance',
        //                 'title' => 'Travel Rule Compliance',
        //                 'message' => 'Do you facilitate or send/receive transfers ≥ $3,000 (Travel Rule)?',
        //                 'type' => 'select',
        //                 'options' => ['Yes', 'No'],
        //                 'required' => true,
        //             ],
        //             [
        //                 'question_id' => 'entity_foreign_correspondent_accounts',
        //                 'title' => 'Foreign Correspondent Accounts',
        //                 'message' => 'Do you maintain any foreign correspondent accounts?',
        //                 'type' => 'select',
        //                 'options' => ['Yes', 'No'],
        //                 'required' => true,
        //             ],
        //             [
        //                 'question_id' => 'entity_private_banking_services',
        //                 'title' => 'Private Banking Services',
        //                 'message' => 'Do you offer private banking services?',
        //                 'type' => 'select',
        //                 'options' => ['Yes', 'No'],
        //                 'required' => true,
        //             ],
        //             [
        //                 'question_id' => 'entity_internet_gambling_gaming',
        //                 'title' => 'Internet Gambling/Gaming',
        //                 'message' => 'Do you support or facilitate internet gambling or gaming?',
        //                 'type' => 'select',
        //                 'options' => ['Yes', 'No'],
        //                 'required' => true,
        //             ],
        //             [
        //                 'question_id' => 'entity_monetary_instruments',
        //                 'title' => 'Monetary Instruments',
        //                 'message' => 'Do you issue or sell monetary instruments?',
        //                 'type' => 'select',
        //                 'options' => ['Yes', 'No'],
        //                 'required' => true,
        //             ],
        //             [
        //                 'question_id' => 'entity_physical_cash_handling',
        //                 'title' => 'Physical Cash Handling',
        //                 'message' => 'Do you deal in or accept physical cash?',
        //                 'type' => 'select',
        //                 'options' => ['Yes', 'No'],
        //                 'required' => true,
        //             ],
        //         ]
        //     ],
        //     [
        //         'section' => 'recordkeeping',
        //         'questions' => [
        //             [
        //                 'question_id' => 'entity_compliance_record_retention_process',
        //                 'title' => 'Compliance Record Retention Process',
        //                 'message' => 'Do you have a process to retain compliance records (e.g., KYC, SARs, alerts)?',
        //                 'type' => 'select',
        //                 'options' => ['Yes', 'No'],
        //                 'required' => true,
        //             ],
        //             [
        //                 'question_id' => 'entity_compliance_record_retention_period',
        //                 'title' => 'Record Retention Period',
        //                 'message' => 'What is your standard record retention period?',
        //                 'type' => 'select',
        //                 'options' => ['5 years', '7 years', 'Other'],
        //                 'required' => true,
        //                 'depends_on' => ['question_id' => 'entity_compliance_record_retention_process', 'value' => 'Yes'],
        //             ],
        //             [
        //                 'question_id' => 'entity_compliance_record_retention_period_other',
        //                 'title' => 'Other Retention Period',
        //                 'message' => 'Please specify your retention period',
        //                 'type' => 'textarea',
        //                 'required' => true,
        //                 'placeholder' => 'Please specify your retention period',
        //                 'depends_on' => ['question_id' => 'entity_compliance_record_retention_period', 'value' => 'Other'],
        //             ],
        //         ]
        //     ],
        // ];

        // // Insert all questions into the database
        // foreach ($questionnaires as $section) {
        //     foreach ($section['questions'] as $question) {
        //         DB::table('questionnaires')->insert([
        //             'section' => $section['section'],
        //             'question_id' => $question['question_id'],
        //             'title' => $question['title'],
        //             'message' => $question['message'] ?? null,
        //             'type' => $question['type'],
        //             'options' => isset($question['options']) ? json_encode($question['options']) : null,
        //             'required' => $question['required'],
        //             'placeholder' => $question['placeholder'] ?? null,
        //             'depends_on' => isset($question['depends_on']) ? json_encode($question['depends_on']) : null,
        //             'created_at' => now(),
        //             'updated_at' => now(),
        //         ]);
        //     }
        // }
        $questionnaires = [
          [
              'title' => 'Business Model Assessment',
              'section' => 'business_model',
              'description' => 'Understand your business model, services, and operational structure',
              'questions' => [
                  [
                      'question' => "Which best describes your company's role?",
                      'type' => 'select',
                      'description' => 'Company Role',
                      'options' => ['Program Manager', 'Sponsor Bank', 'Platform Provider', 'Direct MSB', 'Compliance Vendor', 'Fintech App', 'Other'],
                      'is_required' => true,
                  ],
                  [
                      'question' => 'Describe your role',
                      'type' => 'text',
                      'description' => 'Other Role Description',
                      'is_required' => true,
                  ],
                  [
                      'question' => 'What financial products or services do you offer?',
                      'type' => 'checkbox',
                      'description' => 'Financial Products & Services',
                      'options' => ['Checking/Deposit Accounts', 'Credit/Loans', 'BNPL', 'Debit/Prepaid Cards', 'International Remittances', 'Wire Transfers', 'ACH Payments', 'FX', 'Stablecoins', 'Crypto', 'Digital Wallets', 'Insurance', 'Securities', 'Other'],
                      'is_required' => true,
                  ],
                  [
                      'question' => 'Describe other products or services',
                      'type' => 'textarea',
                      'description' => 'Other Products Description',
                      'is_required' => true,
                  ],
                  [
                      'question' => 'How do customers access your services?',
                      'type' => 'checkbox',
                      'description' => 'Service Delivery Channels',
                      'options' => ['Mobile App', 'Website', 'Physical Branch', 'API/Embedded', 'Agent Network', 'ATM/Kiosk', 'Other'],
                      'is_required' => true,
                  ],
                  [
                      'question' => 'Describe other delivery channels',
                      'type' => 'textarea',
                      'description' => 'Other Delivery Channels',
                      'is_required' => true,
                  ],
                  [
                      'question' => 'What payment rails or funding methods are used?',
                      'type' => 'checkbox',
                      'description' => 'Payment Rails & Funding Methods',
                      'options' => ['ACH', 'Wire', 'Cash', 'Checks', 'Crypto', 'Debit Card', 'Stablecoin', 'Credit Card', 'FX', 'Other'],
                      'is_required' => true,
                  ],
                  [
                      'question' => 'Describe other payment methods',
                      'type' => 'textarea',
                      'description' => 'Other Payment Methods',
                      'is_required' => true,
                  ],
                  [
                      'question' => 'Do you rely on a licensed third party to offer financial services?',
                      'type' => 'select',
                      'description' => 'Third Party Dependencies',
                      'options' => ['Yes', 'No'],
                      'is_required' => true,
                  ],
                  [
                      'question' => 'Enter name and role of third party',
                      'type' => 'textarea',
                      'description' => 'Third Party Details',
                      'is_required' => true,
                  ],
                  [
                      'question' => 'Any additional details about your business model?',
                      'type' => 'textarea',
                      'description' => 'Additional Business Model Details',
                      'is_required' => false,
                  ],
              ]
          ],
          [
              'title' => 'Customer Onboarding & KYC',
              'section' => 'customer_onboarding',
              'description' => 'Details about customer identification, verification, and onboarding procedures',
              'questions' => [
                  [
                      'question' => 'Who are your typical customers?',
                      'type' => 'select',
                      'description' => 'Customer Types',
                      'options' => ['Consumers (individuals)', 'Businesses (entities)', 'Both'],
                      'is_required' => true,
                  ],
                  [
                      'question' => 'What consumer information do you collect and verify?',
                      'type' => 'checkbox',
                      'description' => 'Consumer Information Collection',
                      'options' => ['Full Name', 'Date of Birth', 'Address', 'SSN/TIN', 'Govt ID', 'Selfie/Photo', 'Other'],
                      'is_required' => true,
                  ],
                  [
                      'question' => 'How is consumer identity verified?',
                      'type' => 'select',
                      'description' => 'Consumer Identity Verification',
                      'options' => ['Manual', 'Vendor', 'Both'],
                      'is_required' => true,
                  ],
                  [
                      'question' => 'Consumer KYC vendor (if applicable)',
                      'type' => 'text',
                      'description' => 'Consumer KYC Vendor',
                      'is_required' => false,
                  ],
                  [
                      'question' => 'What business information do you collect and verify?',
                      'type' => 'checkbox',
                      'description' => 'Business Information Collection',
                      'options' => ['Business Name', 'Incorporation Docs', 'EIN/TIN', 'Address', 'UBO Names', 'UBO IDs', 'Control Person', 'Other'],
                      'is_required' => true,
                  ],
                  [
                      'question' => 'How is business identity verified?',
                      'type' => 'select',
                      'description' => 'Business Identity Verification',
                      'options' => ['Manual', 'Vendor', 'Both'],
                      'is_required' => true,
                  ],
                  [
                      'question' => 'Business KYC vendor (if applicable)',
                      'type' => 'text',
                      'description' => 'Business KYC Vendor',
                      'is_required' => false,
                  ],
                  [
                      'question' => 'Where do your customers primarily reside or transact from?',
                      'type' => 'select',
                      'description' => 'Customer Primary Residence',
                      'options' => ['US', 'Canada', 'UK', 'Other'],
                      'is_required' => true,
                  ],
              ]
          ],
          [
              'title' => 'Customer Geography',
              'section' => 'customer_geography',
              'description' => 'Understand customer geographic distribution and high-risk jurisdictions',
              'questions' => [
                  [
                      'question' => 'Where are your customers located?',
                      'type' => 'checkbox',
                      'description' => 'Customer Locations',
                      'options' => ['US', 'Canada', 'Latin America', 'Africa', 'Middle East', 'Asia', 'Europe', 'Other'],
                      'is_required' => true,
                  ],
                  [
                      'question' => 'List other countries or regions',
                      'type' => 'textarea',
                      'description' => 'Other Customer Locations',
                      'is_required' => true,
                  ],
                  [
                      'question' => 'Do you serve or onboard any high-risk customer types or use cases?',
                      'type' => 'checkbox',
                      'description' => 'High-Risk Customer Types',
                      'options' => ['Crypto-related', 'Cross-border Payments', 'Charities/NGOs', 'Gambling', 'Cannabis', 'Other'],
                      'is_required' => true,
                  ],
                  [
                      'question' => 'Describe other high-risk categories',
                      'type' => 'textarea',
                      'description' => 'Other High-Risk Categories',
                      'is_required' => true,
                  ],
                  [
                      'question' => 'Does your company have foreign operations, employees, or offices?',
                      'type' => 'select',
                      'description' => 'Foreign Operations',
                      'options' => ['Yes', 'No'],
                      'is_required' => true,
                  ],
                  [
                      'question' => 'Which countries?',
                      'type' => 'textarea',
                      'description' => 'Foreign Operations Countries',
                      'is_required' => true,
                  ],
              ]
          ],
          [
              'title' => 'Transaction Monitoring',
              'section' => 'transaction_monitoring',
              'description' => 'Details about your transaction monitoring and alert processes',
              'questions' => [
                  [
                      'question' => 'Do you have a transaction monitoring program?',
                      'type' => 'select',
                      'description' => 'Transaction Monitoring Program',
                      'options' => ['Yes', 'No'],
                      'is_required' => true,
                  ],
                  [
                      'question' => 'What types of activity are monitored?',
                      'type' => 'checkbox',
                      'description' => 'Monitored Activity Types',
                      'options' => ['Structuring', 'High Velocity', 'Offshore Wires', 'Unusual Patterns', 'High-Risk Jurisdictions', 'High-Risk MCCs', 'ID Theft', 'Other'],
                      'is_required' => true,
                  ],
                  [
                      'question' => 'Is your monitoring system manual, automated, or both?',
                      'type' => 'select',
                      'description' => 'Monitoring System Type',
                      'options' => ['Manual', 'Automated', 'Hybrid'],
                      'is_required' => true,
                  ],
                  [
                      'question' => 'Who reviews alerts and escalates red flags?',
                      'type' => 'select',
                      'description' => 'Alert Review Process',
                      'options' => ['Compliance Team', 'CCO', 'Operations', 'Other'],
                      'is_required' => true,
                  ],
                  [
                      'question' => 'Who do you report suspicious activity to (if applicable)?',
                      'type' => 'checkbox',
                      'description' => 'Suspicious Activity Reporting',
                      'options' => ['FinCEN', 'Sponsor Bank', 'Internal Only', 'Other'],
                      'is_required' => true,
                  ],
                  [
                      'question' => 'Do you file SARs or UARs?',
                      'type' => 'select',
                      'description' => 'SAR/UAR Filing',
                      'options' => ['Yes', 'No', 'Not Applicable'],
                      'is_required' => true,
                  ],
                  [
                      'question' => 'Additional details about your monitoring or reporting?',
                      'type' => 'textarea',
                      'description' => 'Additional Monitoring Details',
                      'is_required' => false,
                  ],
              ]
          ],
          [
              'title' => 'OFAC & Sanctions Screening',
              'section' => 'ofac_sanctions',
              'description' => 'Sanctions screening and compliance procedures',
              'questions' => [
                  [
                      'question' => 'Do you have a sanctions screening process?',
                      'type' => 'select',
                      'description' => 'Sanctions Screening Process',
                      'options' => ['Yes', 'No'],
                      'is_required' => true,
                  ],
                  [
                      'question' => 'Who or what do you screen?',
                      'type' => 'checkbox',
                      'description' => 'Screening Scope',
                      'options' => ['Customers at onboarding', 'Customers ongoing', 'Transactions', 'Vendors', 'Other'],
                      'is_required' => true,
                  ],
                  [
                      'question' => 'Do you use a vendor for screening?',
                      'type' => 'select',
                      'description' => 'Screening Vendor Usage',
                      'options' => ['Yes', 'No'],
                      'is_required' => true,
                  ],
                  [
                      'question' => 'Screening vendor name',
                      'type' => 'text',
                      'description' => 'Screening Vendor Name',
                      'is_required' => false,
                  ],
                  [
                      'question' => 'Which lists are used?',
                      'type' => 'checkbox',
                      'description' => 'Watchlists Used',
                      'options' => ['OFAC SDN', 'UN', 'EU', 'UK', 'PEP', 'Other'],
                      'is_required' => true,
                  ],
                  [
                      'question' => 'Describe other watchlists',
                      'type' => 'textarea',
                      'description' => 'Other Watchlists',
                      'is_required' => true,
                  ],
                  [
                      'question' => 'How frequently is screening performed?',
                      'type' => 'select',
                      'description' => 'Screening Frequency',
                      'options' => ['Real-Time', 'Daily', 'Weekly', 'Monthly', 'Other'],
                      'is_required' => true,
                  ],
                  [
                      'question' => 'How are potential matches handled?',
                      'type' => 'checkbox',
                      'description' => 'Potential Match Handling',
                      'options' => ['Escalate Internally', 'Block/Reject', 'Report to OFAC', 'Other'],
                      'is_required' => true,
                  ],
                  [
                      'question' => 'How are true matches handled?',
                      'type' => 'checkbox',
                      'description' => 'True Match Handling',
                      'options' => ['Report to Regulator', 'Block', 'Escalate to Bank', 'Other'],
                      'is_required' => true,
                  ],
                  [
                      'question' => 'Anything else you\'d like to share about your screening process?',
                      'type' => 'textarea',
                      'description' => 'Additional Screening Details',
                      'is_required' => false,
                  ],
              ]
          ],
          [
              'title' => 'Customer Due Diligence',
              'section' => 'customer_due_diligence',
              'description' => 'Enhanced due diligence and customer risk classification processes',
              'questions' => [
                  [
                      'question' => 'Do you risk rate or classify your customers?',
                      'type' => 'select',
                      'description' => 'Customer Risk Rating',
                      'options' => ['Yes', 'No'],
                      'is_required' => true,
                  ],
                  [
                      'question' => 'How are customers classified or scored?',
                      'type' => 'checkbox',
                      'description' => 'Customer Risk Classification',
                      'options' => ['Risk Tiering', 'Manual Review', 'Rule-Based System', 'Other'],
                      'is_required' => true,
                  ],
                  [
                      'question' => 'Do you apply Enhanced Due Diligence (EDD) to any customers?',
                      'type' => 'select',
                      'description' => 'Enhanced Due Diligence Application',
                      'options' => ['Yes', 'No'],
                      'is_required' => true,
                  ],
                  [
                      'question' => 'What triggers EDD?',
                      'type' => 'checkbox',
                      'description' => 'EDD Triggers',
                      'options' => ['High-Risk Geography', 'High-Risk Product', 'PEP', 'Adverse Media', 'Large Transactions', 'Internal Decision', 'Other'],
                      'is_required' => true,
                  ],
                  [
                      'question' => 'Describe other EDD triggers',
                      'type' => 'textarea',
                      'description' => 'Other EDD Triggers',
                      'is_required' => true,
                  ],
                  [
                      'question' => 'What steps are included in your EDD process?',
                      'type' => 'checkbox',
                      'description' => 'EDD Process Steps',
                      'options' => ['Additional Documents', 'Senior Review', 'Source of Funds', 'Screening', 'Other'],
                      'is_required' => true,
                  ],
                  [
                      'question' => 'Describe other EDD measures',
                      'type' => 'textarea',
                      'description' => 'Other EDD Measures',
                      'is_required' => true,
                  ],
                  [
                      'question' => 'Do you conduct ongoing monitoring of high-risk customers?',
                      'type' => 'select',
                      'description' => 'Ongoing Monitoring',
                      'options' => ['Yes', 'No'],
                      'is_required' => true,
                  ],
                  [
                      'question' => 'Additional details about your due diligence process?',
                      'type' => 'textarea',
                      'description' => 'Additional Due Diligence Details',
                      'is_required' => false,
                  ],
              ]
          ],
          [
              'title' => 'Training & Governance',
              'section' => 'training_governance',
              'description' => 'BSA/AML training, policies, and governance structures',
              'questions' => [
                  [
                      'question' => 'Do you have a BSA/AML and OFAC training program?',
                      'type' => 'select',
                      'description' => 'BSA/AML and OFAC Training Program',
                      'options' => ['Yes', 'No'],
                      'is_required' => true,
                  ],
                  [
                      'question' => 'Who receives training?',
                      'type' => 'checkbox',
                      'description' => 'Training Audience',
                      'options' => ['Compliance Team', 'All Employees', 'Executives', 'Vendors'],
                      'is_required' => true,
                  ],
                  [
                      'question' => 'How often is training conducted?',
                      'type' => 'select',
                      'description' => 'Training Schedule',
                      'options' => ['At onboarding', 'Annually', 'Other'],
                      'is_required' => true,
                  ],
                  [
                      'question' => 'Is training effectiveness tested?',
                      'type' => 'select',
                      'description' => 'Training Effectiveness Testing',
                      'options' => ['Yes', 'No'],
                      'is_required' => true,
                  ],
                  [
                      'question' => 'Do you retain logs or evidence of training?',
                      'type' => 'select',
                      'description' => 'Training Record Retention',
                      'options' => ['Yes', 'No'],
                      'is_required' => true,
                  ],
                  [
                      'question' => 'Who owns and maintains your compliance policies?',
                      'type' => 'select',
                      'description' => 'Policy Ownership',
                      'options' => ['CCO', 'CEO', 'BOD', 'GC', 'Other'],
                      'is_required' => true,
                  ],
                  [
                      'question' => 'If Other, please explain',
                      'type' => 'textarea',
                      'description' => 'Other Policy Owner',
                      'is_required' => true,
                  ],
              ]
          ],
          [
              'title' => 'Compliance Governance',
              'section' => 'compliance_governance',
              'description' => 'Chief Compliance Officer, board oversight, and independent testing',
              'questions' => [
                  [
                      'question' => 'Do you have a designated Chief Compliance Officer (CCO)?',
                      'type' => 'select',
                      'description' => 'Chief Compliance Officer',
                      'options' => ['Yes', 'No'],
                      'is_required' => true,
                  ],
                  [
                      'question' => 'When was the CCO appointed?',
                      'type' => 'text',
                      'description' => 'CCO Appointment Date',
                      'is_required' => false,
                  ],
                  [
                      'question' => 'Who does the CCO report to?',
                      'type' => 'select',
                      'description' => 'CCO Reporting Line',
                      'options' => ['CEO', 'GC', 'BOD', 'Other'],
                      'is_required' => false,
                  ],
                  [
                      'question' => 'If Other, please explain',
                      'type' => 'textarea',
                      'description' => 'Other CCO Reporting Line',
                      'is_required' => true,
                  ],
                  [
                      'question' => 'Do you have a board or governance committee overseeing compliance?',
                      'type' => 'select',
                      'description' => 'Board Governance Committee',
                      'options' => ['Yes', 'No'],
                      'is_required' => true,
                  ],
                  [
                      'question' => 'Do you conduct independent audits or testing of your compliance program?',
                      'type' => 'select',
                      'description' => 'Independent Testing',
                      'options' => ['Yes', 'Planned', 'No'],
                      'is_required' => true,
                  ],
                  [
                      'question' => 'How frequently is testing performed?',
                      'type' => 'select',
                      'description' => 'Independent Testing Frequency',
                      'options' => ['Annually', 'Every 2 Years', 'As Needed', 'Other'],
                      'is_required' => false,
                  ],
              ]
          ],
          [
              'title' => 'Vendor Oversight & Management',
              'section' => 'vendor_oversight',
              'description' => 'Vendor relationships and compliance oversight',
              'questions' => [
                  [
                      'question' => 'Do you rely on any vendors to support compliance (e.g., KYC, screening, monitoring)?',
                      'type' => 'select',
                      'description' => 'Compliance Vendor Usage',
                      'options' => ['Yes', 'No'],
                      'is_required' => true,
                  ],
                  [
                      'question' => 'How do you evaluate or monitor compliance vendors?',
                      'type' => 'checkbox',
                      'description' => 'Vendor Evaluation Methods',
                      'options' => ['Policy Review', 'Security Due Diligence', 'Periodic Review', 'None'],
                      'is_required' => true,
                  ],
                  [
                      'question' => 'Do you use a system or vendor to maintain compliance records?',
                      'type' => 'select',
                      'description' => 'Compliance Record System',
                      'options' => ['Yes', 'Manual', 'Other'],
                      'is_required' => true,
                  ],
              ]
          ],
          [
              'title' => 'Special Compliance Requirements',
              'section' => 'special_compliance',
              'description' => 'High-risk activities and special regulatory requirements',
              'questions' => [
                  [
                      'question' => 'Do you facilitate or send/receive transfers ≥ $3,000 (Travel Rule)?',
                      'type' => 'select',
                      'description' => 'Travel Rule Compliance',
                      'options' => ['Yes', 'No'],
                      'is_required' => true,
                  ],
                  [
                      'question' => 'Do you maintain any foreign correspondent accounts?',
                      'type' => 'select',
                      'description' => 'Foreign Correspondent Accounts',
                      'options' => ['Yes', 'No'],
                      'is_required' => true,
                  ],
                  [
                      'question' => 'Do you offer private banking services?',
                      'type' => 'select',
                      'description' => 'Private Banking Services',
                      'options' => ['Yes', 'No'],
                      'is_required' => true,
                  ],
                  [
                      'question' => 'Do you support or facilitate internet gambling or gaming?',
                      'type' => 'select',
                      'description' => 'Internet Gambling/Gaming',
                      'options' => ['Yes', 'No'],
                      'is_required' => true,
                  ],
                  [
                      'question' => 'Do you issue or sell monetary instruments?',
                      'type' => 'select',
                      'description' => 'Monetary Instruments',
                      'options' => ['Yes', 'No'],
                      'is_required' => true,
                  ],
                  [
                      'question' => 'Do you deal in or accept physical cash?',
                      'type' => 'select',
                      'description' => 'Physical Cash Handling',
                      'options' => ['Yes', 'No'],
                      'is_required' => true,
                  ],
              ]
          ],
          [
              'title' => 'Record Keeping & Retention',
              'section' => 'recordkeeping',
              'description' => 'Compliance record retention policies and procedures',
              'questions' => [
                  [
                      'question' => 'Do you have a process to retain compliance records (e.g., KYC, SARs, alerts)?',
                      'type' => 'select',
                      'description' => 'Compliance Record Retention Process',
                      'options' => ['Yes', 'No'],
                      'is_required' => true,
                  ],
                  [
                      'question' => 'What is your standard record retention period?',
                      'type' => 'select',
                      'description' => 'Record Retention Period',
                      'options' => ['5 years', '7 years', 'Other'],
                      'is_required' => true,
                  ],
                  [
                      'question' => 'Please specify your retention period',
                      'type' => 'textarea',
                      'description' => 'Other Retention Period',
                      'is_required' => true,
                  ],
              ]
          ],
        ];

        // Create questionnaires with their questions
        foreach ($questionnaires as $index => $questionnaireData) {
            $questions = $questionnaireData['questions'];
            unset($questionnaireData['questions']);

            // Create the questionnaire
            $questionnaire = Questionnaire::create([
                'title' => $questionnaireData['title'],
                'section' => $questionnaireData['section'],
                'description' => $questionnaireData['description'],
                'start_date' => now(),
                'end_date' => now()->addMonths(3),
                'allow_anonymous' => false,
                'allow_multiple_responses' => false,
                'show_progress' => true,
                'randomize_questions' => false,
                'status' => 'active',
                'user_id' => 1, // Default admin user ID
            ]);

            // Create questions for this questionnaire
            foreach ($questions as $questionIndex => $questionData) {
                Question::create([
                    'questionnaire_id' => $questionnaire->id,
                    'question' => $questionData['question'],
                    'type' => $questionData['type'],
                    'description' => $questionData['description'] ?? null,
                    'options' => isset($questionData['options']) ? json_encode($questionData['options']) : null,
                    'is_required' => $questionData['is_required'] ?? false,
                    'order' => $questionIndex + 1,
                ]);
            }
        }
    }
}
